Update test1

diff --git a/test1 b/test1
--- a/test1
+++ b/test1
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
+# Copyright (c) 2021-2024 tteck
+# Author: tteck (tteckster)
+# License: MIT
+# https://github.com/tteck/Proxmox/raw/main/LICENSE
 
 function header_info {
-    clear
-    cat <<"EOF"
+  clear
+  cat <<"EOF"
  ______              __ __           __   _  _______
 /_  __/_ _________  / //_/__ __ __  / /  | |/_/ ___/
  / / / // / __/ _ \/ ,< / -_) // / / /___>  </ /__
@@ -16,97 +20,79 @@ shopt -s expand_aliases
 alias die='EXIT=$? LINE=$LINENO error_exit'
 trap die ERR
 function error_exit() {
-    trap - ERR
-    local DEFAULT='Unknown failure occurred.'
-    local REASON="\e[97m${1:-$DEFAULT}\e[39m"
-    local FLAG="\e[91m[ERROR] \e[93m$EXIT@$LINE"
-    msg "$FLAG $REASON" 1>&2
-    [ ! -z ${CTID-} ] && cleanup_ctid
-    exit $EXIT
+  trap - ERR
+  local DEFAULT='Unknown failure occurred.'
+  local REASON="\e[97m${1:-$DEFAULT}\e[39m"
+  local FLAG="\e[91m[ERROR] \e[93m$EXIT@$LINE"
+  msg "$FLAG $REASON" 1>&2
+  [ ! -z ${CTID-} ] && cleanup_ctid
+  exit $EXIT
 }
 function warn() {
-    local REASON="\e[97m$1\e[39m"
-    local FLAG="\e[93m[WARNING]\e[39m"
-    msg "$FLAG $REASON"
+  local REASON="\e[97m$1\e[39m"
+  local FLAG="\e[93m[WARNING]\e[39m"
+  msg "$FLAG $REASON"
 }
 function info() {
-    local REASON="$1"
-    local FLAG="\e[36m[INFO]\e[39m"
-    msg "$FLAG $REASON"
+  local REASON="$1"
+  local FLAG="\e[36m[INFO]\e[39m"
+  msg "$FLAG $REASON"
 }
 function msg() {
-    local TEXT="$1"
-    echo -e "$TEXT"
+  local TEXT="$1"
+  echo -e "$TEXT"
 }
 function cleanup_ctid() {
-    if pct status $CTID &>/dev/null; then
-        if [ "$(pct status $CTID | awk '{print $2}')" == "running" ]; then
-            pct stop $CTID
-        fi
-        pct destroy $CTID
+  if pct status $CTID &>/dev/null; then
+    if [ "$(pct status $CTID | awk '{print $2}')" == "running" ]; then
+      pct stop $CTID
     fi
+    pct destroy $CTID
+  fi
 }
 
-# Function to select storage
-function select_storage() {
-    local CLASS=$1
-    local CONTENT
-    local CONTENT_LABEL
-    case $CLASS in
-        container)
-            CONTENT='rootdir'
-            CONTENT_LABEL='Container'
-            ;;
-        template)
-            CONTENT='vztmpl'
-            CONTENT_LABEL='Container template'
-            ;;
-        *)
-            false || die "Invalid storage class."
-            ;;
-    esac
-
-    # Query all storage locations
-    local MENU
-    local MSG_MAX_LENGTH=0
-    while read -r line; do
-        local TAG=$(echo $line | awk '{print $1}')
-        local TYPE=$(echo $line | awk '{printf "%-10s", $2}')
-        local FREE=$(echo $line | numfmt --field 4-6 --from-unit=K --to=iec --format %.2f | awk '{printf( "%9sB", $6)}')
-        local ITEM="  Type: $TYPE Free: $FREE "
-        local OFFSET=2
-        if [[ $((${#ITEM} + $OFFSET)) -gt ${MSG_MAX_LENGTH:-} ]]; then
-            MSG_MAX_LENGTH=$((${#ITEM} + $OFFSET))
-        fi
-        MENU+=("$TAG" "$ITEM" "OFF")
-    done < <(pvesm status -content $CONTENT | awk 'NR>1')
-
-    # Select storage location
-    if [ $((${#MENU[@]} / 3)) -eq 0 ]; then
-        warn "'$CONTENT_LABEL' needs to be selected for at least one storage location."
-        die "Unable to detect valid storage location."
-    elif [ $((${#MENU[@]} / 3)) -eq 1 ]; then
-        printf ${MENU[0]}
-    else
-        local STORAGE
-        while [ -z "${STORAGE:+x}" ]; do
-            STORAGE=$(whiptail --backtitle "Proxmox VE Helper Scripts" --title "Storage Pools" --radiolist \
-            "Which storage pool you would like to use for the ${CONTENT_LABEL,,}?\n\n" \
-            16 $(($MSG_MAX_LENGTH + 23)) 6 \
-            "${MENU[@]}" 3>&1 1>&2 2>&3) || die "Menu aborted."
-        done
-        printf $STORAGE
-    fi
-}
-
-# Get template storage
-function get_template_storage() {
-    select_storage "template"
-}
-
-# Get container storage
-function get_container_storage() {
-    select_storage "container"
+# Stop Proxmox VE Monitor-All if running
+if systemctl is-active -q ping-instances.service; then
+  systemctl stop ping-instances.service
+fi
+header_info
+whiptail --backtitle "Proxmox VE Helper Scripts" --title "TurnKey LXCs" --yesno "This will allow for the creation of one of the many TurnKey LXC Containers. Proceed?" 10 68 || exit
+TURNKEY_MENU=()
+MSG_MAX_LENGTH=0
+while read -r TAG ITEM; do
+  OFFSET=2
+  ((${#ITEM} + OFFSET > MSG_MAX_LENGTH)) && MSG_MAX_LENGTH=${#ITEM}+OFFSET
+  TURNKEY_MENU+=("$TAG" "$ITEM " "OFF")
+done < <(
+  cat <<EOF
+ansible Ansible
+bookstack BookStack
+core Core
+faveo-helpdesk Faveo Helpdesk
+fileserver File Server
+gallery Gallery
+gameserver Game Server
+gitea Gitea
+gitlab GitLab
+invoice-ninja Invoice Ninja
+mediaserver Media Server
+nextcloud Nextcloud
+observium Observium
+odoo Odoo
+openvpn OpenVPN
+owncloud ownCloud
+phpbb phpBB
+torrentserver Torrent Server
+wireguard WireGuard
+wordpress Wordpress
+zoneminder ZoneMinder
+EOF
+)
+turnkey=$(whiptail --backtitle "Proxmox VE Helper Scripts" --title "TurnKey LXCs" --radiolist "\nSelect a TurnKey LXC to create:\n" 16 $((MSG_MAX_LENGTH + 58)) 6 "${TURNKEY_MENU[@]}" 3>&1 1>&2 2>&3 | tr -d '"') || exit
+[ -z "$turnkey" ] && {
+  whiptail --backtitle "Proxmox VE Helper Scripts" --title "No TurnKey LXC Selected" --msgbox "It appears that no TurnKey LXC container was selected" 10 68
+  msg "Done"
+  exit
 }
 
 # Main function to create LXC container
@@ -141,14 +127,10 @@ function create_container() {
     msg "Updating LXC template list..."
     pveam update >/dev/null
 
-    # Get LXC template string
-    local TEMPLATES
-    mapfile -t TEMPLATES < <(pveam available -section turnkeylinux | awk -v turnkey="${turnkey}" '$0 ~ turnkey {print $2}' | sort -t - -k 2 -V)
-    [ ${#TEMPLATES[@]} -gt 0 ] || die "Unable to find a template when searching for '${turnkey}'."
-    local TEMPLATE="${TEMPLATES[-1]}"
-
-    # Download LXC template
+    # Check if template is already downloaded
+    local TEMPLATE="${turnkey}"
     if ! pveam list $TEMPLATE_STORAGE | grep -q $TEMPLATE; then
+        # Template not downloaded, download it
         msg "Downloading LXC template (Patience)..."
         pveam download $TEMPLATE_STORAGE $TEMPLATE >/dev/null ||
         die "A problem occurred while downloading the LXC template."
@@ -160,7 +142,7 @@ function create_container() {
 
     # Create LXC
     msg "Creating LXC container..."
-    pct create $CTID ${TEMPLATE_STORAGE}:vztmpl/${TEMPLATE} ${PCT_OPTIONS[@]} >/dev/null ||
+    pct create $CTID ${TEMPLATE_STORAGE}:$TEMPLATE ${PCT_OPTIONS[@]} >/dev/null ||
     die "A problem occurred while trying to create the container."
 
     # Save password
@@ -209,22 +191,64 @@ function create_container() {
     echo
 }
 
-# Main function
-function main() {
-    header_info
-    echo -e "Loading..."
-
-    # Stop Proxmox VE Monitor-All if running
-    if systemctl is-active -q ping-instances.service; then
-        systemctl stop ping-instances.service
-    fi
-
-    # Prompt for TurnKey LXC selection
-    whiptail --backtitle "Proxmox VE Helper Scripts" --title "TurnKey LXCs" --yesno "This will allow for the creation of one of the many TurnKey LXC Containers. Proceed?" 10 68 || exit
-
-    # Create LXC container
-    create_container
+# Get template storage
+function get_template_storage() {
+    select_storage template
 }
 
-# Execute main function
-main
+# Get container storage
+function get_container_storage() {
+    select_storage container
+}
+
+# Set the CONTENT and CONTENT_LABEL variables
+function select_storage() {
+    local CLASS=$1
+    local CONTENT
+    local CONTENT_LABEL
+    case $CLASS in
+    container)
+        CONTENT='rootdir'
+        CONTENT_LABEL='Container'
+        ;;
+    template)
+        CONTENT='vztmpl'
+        CONTENT_LABEL='Container template'
+        ;;
+    *) false || die "Invalid storage class." ;;
+    esac
+
+    # Query all storage locations
+    local -a MENU
+    while read -r line; do
+        local TAG=$(echo $line | awk '{print $1}')
+        local TYPE=$(echo $line | awk '{printf "%-10s", $2}')
+        local FREE=$(echo $line | numfmt --field 4-6 --from-unit=K --to=iec --format %.2f | awk '{printf( "%9sB", $6)}')
+        local ITEM="  Type: $TYPE Free: $FREE "
+        local OFFSET=2
+        if [[ $((${#ITEM} + $OFFSET)) -gt ${MSG_MAX_LENGTH:-} ]]; then
+            local MSG_MAX_LENGTH=$((${#ITEM} + $OFFSET))
+        fi
+        MENU+=("$TAG" "$ITEM" "OFF")
+    done < <(pvesm status -content $CONTENT | awk 'NR>1')
+
+    # Select storage location
+    if [ $((${#MENU[@]} / 3)) -eq 0 ]; then
+        warn "'$CONTENT_LABEL' needs to be selected for at least one storage location."
+        die "Unable to detect valid storage location."
+    elif [ $((${#MENU[@]} / 3)) -eq 1 ]; then
+        printf ${MENU[0]}
+    else
+        local STORAGE
+        while [ -z "${STORAGE:+x}" ]; do
+            STORAGE=$(whiptail --backtitle "Proxmox VE Helper Scripts" --title "Storage Pools" --radiolist \
+                "Which storage pool you would like to use for the ${CONTENT_LABEL,,}?\n\n" \
+                16 $(($MSG_MAX_LENGTH + 23)) 6 \
+                "${MENU[@]}" 3>&1 1>&2 2>&3) || die "Menu aborted."
+        done
+        printf $STORAGE
+    fi
+}
+
+# Call the function to create the container
+create_container
